blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: https://github.com/adefee/Andy-ESO/discussions
    about: Ask questions or discuss Andy in our GitHub Discussions
  - name: Feature Requests
    url: https://github.com/adefee/Andy-ESO/discussions/new?category=ideas
    about: Suggest new features or improvements for Andy

